import { NestFactory } from '@nestjs/core';
import { Logger } from '@nestjs/common';
import * as bcrypt from 'bcryptjs';
import { AppModule } from '../../app.module';
import { User } from '../../entities/user.entity';
import { Blog } from '../../entities/blog.entity';
import AppDataSource from '../../../typeorm.config';

async function seed() {
  const logger = new Logger('Seeder');
  const app = await NestFactory.createApplicationContext(AppModule);

  try {
    logger.log('Starting database seeding...');

    await AppDataSource.initialize();

    // Get repositories
    const userRepository = AppDataSource.getRepository(User);
    const blogRepository = AppDataSource.getRepository(Blog);

    // Create demo users
    const users = await Promise.all([
      userRepository.save({
        email: 'jason@repurpose.com',
        username: 'jason',
        password: await bcrypt.hash('password123', 10),
      }),
      userRepository.save({
        email: 'anurag@gmail.com',
        username: 'anurag',
        password: await bcrypt.hash('password321', 10),
      }),
    ]);

    // Create demo blogs
    // Note.: Generated by ChatGPT, dont really wanna read my own writing, even for a sample app
    const blogs = await Promise.all([
      blogRepository.save({
        title: 'Why Plastic Waste Matters',
        content:
          'Every year, over 300 million tons of plastic are produced—half of it single-use. Most ends up in landfills or the ocean, harming wildlife and entering our food chain. Solving plastic pollution starts with awareness. Reducing, reusing, and proper recycling are powerful everyday actions we all can take.',
        author: users[0],
      }),
      blogRepository.save({
        title: 'What Happens to Recycled Plastic',
        content:
          "When you toss plastic into a recycling bin, it doesn't magically disappear. It's sorted, cleaned, shredded, melted, and molded into new products—if it's a type that your local facility accepts. Unfortunately, not all plastic gets recycled. Knowing your local recycling codes can make a real difference.",
        author: users[1],
      }),
      blogRepository.save({
        title: 'Understanding Recycling Symbols',
        content:
          "The numbers inside the recycling triangle (♻️) aren't all created equal. #1 (PET): Common in bottles; widely recycled. #2 (HDPE): Used in milk jugs; recyclable. #6 (PS): Found in foam cups; rarely recycled. Learning the codes helps you sort smarter and waste less.",
        author: users[0],
      }),
      blogRepository.save({
        title: 'How to Sort Plastic at Home',
        content:
          'Not all plastics belong together! Mixing unrecyclable plastic with recyclables can contaminate the entire batch. Rinse containers, remove labels if required, and separate plastic by type. A few extra seconds at home can save hours (and resources) later in the recycling chain.',
        author: users[0],
      }),
      blogRepository.save({
        title: 'What Are Plastic Offsets',
        content:
          "Plastic offsets work like carbon credits: for every unit of plastic you use, you support programs that collect or recycle an equal (or greater) amount elsewhere. It's a way to take responsibility for your footprint—especially for individuals or brands that can't avoid plastic use completely.",
        author: users[1],
      }),
      blogRepository.save({
        title: 'Things Made from Recycled Plastic',
        content:
          "Recycled plastic isn't just used in bottles again. It's being transformed into: Road surfaces Outdoor furniture Synthetic clothing fibers Construction bricks These innovations give waste a second life and reduce the need for virgin plastic.",
        author: users[0],
      }),
      blogRepository.save({
        title: 'The Cost of Single-Use Plastic',
        content:
          "Plastic straws, cutlery, and bags may be convenient—but they're used for minutes and last centuries in the environment. Switching to reusable items and saying 'no' to unnecessary plastic is a simple yet powerful way to cut your impact.",
        author: users[0],
      }),
    ]);

    logger.log(`Created ${users.length} users`);
    logger.log(`Created ${blogs.length} blogs`);
    logger.log('Database seeding completed successfully');
  } catch (error) {
    logger.error('Error during database seeding:', error);
    throw error;
  } finally {
    await AppDataSource.destroy();
    await app.close();
  }
}

void seed();
